### PR TITLE
Feat: Changelog's page

### PR DESCRIPTION
**Pull request by melnikga**
A new Changelog page has been added, header with links in both the desktop and mobile versions has been updated.

Checklist for @mazurroman before merging:
- [ ] Add flag to the "Get updates" so that mailchimp differentiates these emails from the landing page emails

### CODE REVIEW

**Comment by mazurroman** [comment]
**Great start! Suggestions for improvements:**
* Can we make the left side of the screen dark, with the same style and image as original commit template
* Dates are too large - let's style them similarly to the original template
* Can we make the "Get updated" email form work? Same way as the form on the walnut.dev form on homepage
* Remove "Documentation" and "RSS" as those are not working. Instead let's use Twitter (@walnut_dev) and Telegram (@walnutcorestars)
* Github should open walnuthq on github
* Remove "Brought to you by" section
* On the original template (https://commit.tailwindui.com/) the buttons like "RSS" have a blue hover effect. Can we have the same effect but make it pink so that it's more onbrand with walnut. Same for all other hover effects on the page.

**Copy:**
* Title: Debugger for Starknet
* Description: Delve deeper into Cairo transaction execution, swiftly identifying bugs and pinpointing areas for improvement.

Also, one bug: on my local computer, there is a scroll bar on the left part of the screen. Can we get rid of the scroll bar?

**Comment by melnikga** [comment]
@mazurroman I completely agree with all the edits. I will be able to make changes to the PR tomorrow.

**Comment by melnikga** [comment]
@mazurroman 
I've made all the edits from your previous comment

**Review by mazurroman — APPROVED** [review]
lgtm!

**Pull request merged**
